services:
  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    container_name: hospital_backend
    ports:
      - "8000:8000"
    env_file:
      - ./BACKEND/.env
    volumes:
      - ./BACKEND:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - hospital_network

  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    container_name: hospital_frontend
    ports:
      - "3003:3003"
    env_file:
      - ./FRONTEND/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./FRONTEND:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - hospital_network
    stdin_open: true
    tty: true

networks:
  hospital_network:
    driver: bridge

